### ISSUE TITLE
Unable to export .blend as .vrm

### ISSUE THREAD

**Issue by Krutonium** [kitsune-ONE-team/KITSUNETSUKI-Asset-Tools#2] opened 2021-11-08 04:28 UTC
```
(base) C:\Users\pfckr>blend2vrm --output synth.vrm "C:\Users\pfckr\Downloads\Framework the Synth 4.blend"
Color management: using fallback mode for management
Color management: Error could not find role data role.
Color management: scene view "Filmic" not found, setting default "Standard".
Read blend: C:\Users\pfckr\Downloads\Framework the Synth 4.blend
Color management: scene view "Filmic" not found, setting default "Standard".
Traceback (most recent call last):
  File "c:\users\pfckr\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pfckr\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pfckr\miniconda3\Scripts\blend2vrm.exe\__main__.py", line 7, in <module>
  File "c:\users\pfckr\miniconda3\lib\site-packages\kitsunetsuki\blend2vrm.py", line 90, in main
    out, buf = e.convert()
  File "c:\users\pfckr\miniconda3\lib\site-packages\kitsunetsuki\exporter\vrm\__init__.py", line 258, in convert
    root, buffer_ = super().convert()
  File "c:\users\pfckr\miniconda3\lib\site-packages\kitsunetsuki\exporter\gltf\__init__.py", line 482, in convert
    root = super().convert()
  File "c:\users\pfckr\miniconda3\lib\site-packages\kitsunetsuki\exporter\base\__init__.py", line 186, in convert
    self._root = self.make_root_node()
  File "c:\users\pfckr\miniconda3\lib\site-packages\kitsunetsuki\exporter\vrm\__init__.py", line 76, in make_root_node
    'title': data['meta']['title'],
KeyError: 'meta'
```

TBH I have no idea how to interpret this.

**Comment by sagefreeman** [comment] 2021-11-27 16:32
I was able to reproduce this error using Blender v2.93.6. Hoping there is a fix for this soon :-)

**Comment by supertin** [comment] 2022-02-01 11:22
+1
Is it because of the Blender version (I'm on 2.93.3 on Ubuntu) or because none of us know how to work this addon?

**Comment by jurassicjordan** [comment] 2022-03-07 22:18
problem still happens in blender 3.0.1 when will this be fixed?

**Comment by Yonnji** [comment] 2022-06-14 13:47
You need to create a text block called "VRM.ini"
Yon can check the example here - 
https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/blob/master/blend2vrm.md#vrm-meta-info-template
You can also check .blend file which already have the text block already prepared - 
https://github.com/kitsune-ONE-team/KITSUNETSUKI-Asset-Tools/blob/master/examples/vrm/latifa_v2.blend.xz

**Closed as completed** 2022-11-11 17:51 UTC
